# Ports are host:container
services:
  reverse-proxy:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    command: ["nginx", "-g", "daemon off;"]
    depends_on:
      - frontend
      - api
    ports:
      - "3000:3000"
    networks:
      - main

  api:
    build:
      context: ./api
      target: dev
    volumes:
      - ./api:/app
      - /app/node_modules
      - /app/.next
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NEXT_WEBPACK_USEPOLLING=1
      - WATCHPACK_POLLING=true
    env_file:
      - ./envFiles/.env
    command: sh -c "npm i && npm run ${API_RUN_SCRIPT}"
    # depends_on:
    #   - auth
    networks:
      - main

  frontend:
    build:
      context: ./frontend
      target: dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - ./envFiles/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NEXT_WEBPACK_USEPOLLING=1
      - WATCHPACK_POLLING=true

    command: sh -c "npm i && npm run ${FRONTEND_RUN_SCRIPT}"
    depends_on:
      - api
    networks:
      - main

  database:
    image: postgres
    restart: always
    shm_size: 128mb
    env_file:
      - ./envFiles/.env
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - main
  ### Auth service
  auth_api:
    build:
      context: ./auth/api
      target: dev
    command: sh -c "python main.py"
    volumes:
      - ./auth/api/src:/app
      - /app/venv
    env_file:
      - ./envFiles/.auth.env
    networks:
      - main
    depends_on:
      - auth_db
  auth_db:
    image: postgres
    restart: always
    shm_size: 128mb
    env_file:
      - ./envFiles/.auth.env
    volumes:
      - ./auth/db:/docker-entrypoint-initdb.d
    networks:
      - main
    ports:
      - "5432:5432"
  auth_frontend:
    build:
      context: ./auth/frontend
      target: dev
    volumes:
      - ./auth/frontend:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - ./envFiles/.auth.env
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NEXT_WEBPACK_USEPOLLING=1
      - WATCHPACK_POLLING=true
    command: sh -c "npm i && npm run ${FRONTEND_RUN_SCRIPT}"
    depends_on:
      - auth_api
    networks:
      - main

networks:
  main:
    driver: bridge
volumes:
  frontend_node_modules:
