# Ports are host:container
services:
  reverse-proxy:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    command: ["nginx", "-g", "daemon off;"]
    depends_on:
      - frontend
      # - api
    ports:
      - "3000:3000"
  # api:
  #   build:
  #     context: ./api
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5001:5000"
  frontend:
    build: 
      context: ./frontend
      target: dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    # ports:
    #  - "5000:3000"
    env_file:
      - ./envFiles/.frontend.env
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NEXT_WEBPACK_USEPOLLING=1
      - WATCHPACK_POLLING=true

    command: sh -c "npm i && npm run ${FRONTEND_RUN_SCRIPT}"
  # auth:
  #   build:
  #     context: ./auth
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5002:5000"

  database:
    image: postgres
    restart: always
    shm_size: 128mb
    env_file:
      - ./envFiles/.db.env

volumes:
  frontend_node_modules: